### ISSUE TITLE
[Feature request] Automatically select Paket tab on page load

### ISSUE THREAD

**Issue by pmbanka** [SeanKilleen/paket-attacket#2]
I guess all users of the extension are Paket users anyway?

**Comment by ghuntley** [comment]
😆

**Comment by SeanKilleen** [comment]
Ha! Sure, might make sense to consider this. One of the things stopping me is that I had to pull a bunch of the non-minified code from the nuget gallery repo to reproduce what they're doing. 

I'll have to look into what they're doing to select Nuget as the default installer (is it hard-coded? Some JS function? An if statement somewhere on generation?) to figure it out.

If anyone wants to find the answer, feel free to post it here. OR, alternatively, I'd accept a PR. :)

**Comment by pmbanka** [comment]
@SeanKilleen Is the new version released already to Chrome Web Store?

**Comment by SeanKilleen** [comment]
@pmbanka it is; however, I just noticed it's still "publishing" on their end. Give it a few minutes and it should show up as the latest release.

**Comment by SeanKilleen** [comment]
Chrome store link, FYI: https://chrome.google.com/webstore/detail/paket-attaket/cahelnnmpipkglekhnoagfjgnelmeakd?hl=en-US

**Comment by pmbanka** [comment]
I just updated. Thanks a lot 💯
